name: CI

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  cargo-format:
    name: Cargo Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Lint
        run: cargo fmt --check

  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test
